version: '2'
services:
  # run docker-compose up -d, to run storefile-transforms
  # local service dependencies -- great for testing.
  nsqlookupd:
    image: nsqio/nsq
    restart: always
    ports:
      - "4160:4160"
      - "4161:4161"
    command: 'nsqlookupd'

  nsqd:
    image: nsqio/nsq
    restart: always
    ports:
      - "4150:4150"
      - "4151:4151"
    command: nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=0.0.0.0
